spring:
  application:
    name: forohub

  datasource:
    url: jdbc:postgresql://${DB_HOST}/forohub
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    jwt:
      secret: ${JWT_SECRET}
