spring:
  application:
    name: forohub

  datasource:
    url: ${DB_DATASOURCE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    jwt:
      secret: ${JWT_SECRET}

server:
  error:
    include-stacktrace: never
